### ISSUE TITLE
Robot disassemble itself

### ISSUE THREAD

**Issue by ghost** [squirrel-project/squirrel_common#207]
Hi,
I think something is going wrong here :)
![issue2](https://user-images.githubusercontent.com/2829645/28118841-0b54650a-6713-11e7-983c-44036a0a285a.png)

**Comment by ipa-nhg** [comment]
this is our 8 dof controller :)

at the moment for the simulation there is a fast-fix model that has to be redone as soon as the new real arm driver with the base position controller is integrated. what you need to test?  If you want just to test navigation you can use other platform simulation instead of alufr-robotino

**Comment by ghost** [comment]
Ah ok.
I noticed this happens just commanding the base (I was just wandering if the laser readings get screwed up)

**Comment by ghost** [comment]
Is there any workaround for this? I would like to test the navigation with changeable footprints.

**Comment by ipa-nhg** [comment]
I did a hot fix: https://github.com/squirrel-project/squirrel_robotino/pull/196 and https://github.com/squirrel-project/squirrel_common/pull/209 

Just pull squirrel_robotino and squirrel_common from me (ipa-nhg) and the branch HotFix:

git pull https://github.com/ipa-nhg/squirrel_common HotFix
git pull https://github.com/ipa-nhg/squirrel_robotino HotFix

I hope this is enough!

**Comment by ipa-nhg** [comment]
Solved
